version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    ports:
      - "9000:9000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    environment:
      PORT: 9000
      NODE_ENV: production
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "27017:27017"
